apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: oauth2-proxy
 namespace: egov
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: oauth2-proxy
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 80
