apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: egov-user
 namespace: egov
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: egov-user
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 80
