# Common Labels
labels:
  app: "egov-filemgmnt"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  context: "filemgmnt"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "filemgmnt_services_schema"
    image:
      repository: "egov-filemgmnt-db"

# Container Configs
image:
  repository: "egov-filemgmnt"
replicas: "1"
healthChecks:
  enabled: false
  livenessProbePath: "/filemgmnt/health"
  readinessProbePath: "/filemgmnt/health"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: WORKFLOW_CONTEXT_PATH
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url
  - name: FLYWAY_ENABLED
    value: "false"
  - name: SPRING_FLYWAY_ENABLED
    value: "false"
  - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH
    value: "/"
  - name: APP_TIMEZONE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: timezone 
  - name: FLYWAY_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: SPRING_DATASOURCE_TOMCAT_INITIAL_SIZE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: spring-datasource-tomcat-initialSize
  - name: SERVER_TOMCAT_MAX_THREADS
    {{- if index .Values "server-tomcat-max-threads" }} 
      value: {{ index .Values "server-tomcat-max-threads" | quote }}    
    {{- else }}        
      valueFrom:
        configMapKeyRef:
          name: egov-config
          key: server-tomcat-max-threads
    {{- end }}            
  - name: SERVER_TOMCAT_MAX_CONNECTIONS
  {{- if index .Values "server-tomcat-max-connections" }} 
    value: {{ index .Values "server-tomcat-max-connections" | quote }}    
  {{- else }}        
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: server-tomcat-max-connections
  {{- end }}                
  - name: SPRING_DATASOURCE_TOMCAT_MAX_ACTIVE
  {{- if index .Values "spring-datasource-tomcat-max-active" }}
    value: {{ index .Values "spring-datasource-tomcat-max-active" | quote }}
  {{- else }} 
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: spring-datasource-tomcat-max-active 
  {{- end }}       
  - name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
  {{- if index .Values "spring-datasource-tomcat-max-active" }}
    value: {{ index .Values "spring-datasource-tomcat-max-active" | quote }}
  {{- else }}
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: spring-datasource-tomcat-max-active 
  {{- end }}           
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: SPRING_JPA_SHOW_SQL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: spring-jpa-show-sql    