# Common Labels
labels:
  app: "egov-filemgmnt"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  context: "egov-filemgmnt-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "filemgmnt_services_schema"
    image:
      repository: "egov-filemgmnt-db"

# Container Configs
image:
  repository: "egov-filemgmnt"
replicas: "1"
healthChecks:
  enabled: false
  livenessProbePath: "/egov-filemgmnt-services/health"
  readinessProbePath: "/egov-filemgmnt-services/health"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: WORKFLOW_CONTEXT_PATH
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
        