# Common Labels
labels:
  app: "kssm-snehapoorvam"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "kssm-snehapoorvam"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "kssm-snehapoorvam_schema"
    image:
      repository: "kssm-snehapoorvam-db"

# Container Configs
image:
  repository: "kssm-snehapoorvam"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/kssm-snehapoorvam/health"
  readinessProbePath: "/kssm-snehapoorvam/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"



resources: |
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 784Mi
    cpu: 300m


# Additional Container Envs
env: |
  - name: SERVER_CONTEXTPATH
    value: /kssm-snehapoorvam
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: kssm-snehapoorvam
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: KAFKA_TOPICS_SAVE_SERVICE
    value: save-snehapoorvam-topic
  - name: KAFKA_TOPICS_UPDATE_SERVICE
    value: update-snehapoorvam-topic
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_ENC_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_PDF_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-pdf
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_WORKFLOW_PATH
    value: "egov-workflow-v2/egov-wf/process/_transition"
  - name: EGOV_COLLECTION_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: collection-services
  - name: EGOV_PDFSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pdf-service
  - name: EGOV_STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_BND_FREEDOWNLOAD_TENANTS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-bnd-freedownload-tenants
  - name: EGOV_BND_LIVE_CITIZEN_TENANTS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-bnd-live-citizen-tenants
  - name: EGOV_UI_APP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
